version: "3"
services:
  mongo_db:
    container_name: mongo_db
    image: "mongo:latest"
    restart: always
    volumes:
      - mongo_db:/data/db
    ports:
      - 27017:27017

  nodejs-app:
    build: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      APP_NAME: Safety
      PORT: 3000
      DB_URI: mongodb://mongo_db:27017/safetyChat
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
